## Importação dos pacotes

In [1]:
# importar pacotes necessários
import numpy as np
import pandas as pd

In [2]:
# definir parâmetros extras
pd.set_option('precision', 4)
pd.set_option('display.max_columns', 100)

## Carga dos dados

In [3]:
# carregar arquivo de dados de treino
data = pd.read_csv('abalone-train.csv', index_col='id')

# mostrar alguns exemplos de registros
data.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
id,,,,,,,,,
2758,M,0.535,0.430,0.155,0.7845,0.3285,0.1690,0.2450,10
1384,F,0.630,0.485,0.170,1.3205,0.5945,0.3450,0.3450,9
1131,M,0.565,0.435,0.150,0.9900,0.5795,0.1825,0.2060,8
3726,I,0.500,0.395,0.145,0.7865,0.3320,0.1815,0.2455,8
3445,I,0.495,0.400,0.145,0.5780,0.2545,0.1305,0.1645,8

In [4]:
# quantas linhas e colunas existem?
data.shape

(2784, 9)

## Análise dos dados

In [5]:
# quais são as colunas e respectivos tipos de dados?
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2784 entries, 2758 to 852
Data columns (total 9 columns):
sex               2784 non-null object
length            2784 non-null float64
diameter          2784 non-null float64
height            2784 non-null float64
whole_weight      2784 non-null float64
shucked_weight    2784 non-null float64
viscera_weight    2784 non-null float64
shell_weight      2784 non-null float64
rings             2784 non-null int64
dtypes: float64(7), int64(1), object(1)
memory usage: 206.6+ KB

In [6]:
# existem colunas com dados nulos?
data[data.columns[data.isnull().any()]].isnull().sum()

Series([], dtype: float64)

In [7]:
# sumário estatístico das características numéricas
data.describe().T

,count,mean,std,min,25%,50%,75%,max
length,2784.0,0.5218,0.1198,0.0750,0.4500,0.5400,0.6100,0.8150
diameter,2784.0,0.4059,0.0988,0.0550,0.3450,0.4200,0.4800,0.6500
height,2784.0,0.1387,0.0388,0.0000,0.1100,0.1400,0.1650,0.5150
whole_weight,2784.0,0.8168,0.4837,0.0020,0.4351,0.7853,1.1360,2.7795
shucked_weight,2784.0,0.3548,0.2186,0.0010,0.1819,0.3320,0.4981,1.3485
viscera_weight,2784.0,0.1781,0.1086,0.0005,0.0910,0.1675,0.2471,0.7600
shell_weight,2784.0,0.2347,0.1360,0.0015,0.1258,0.2300,0.3221,0.8850
rings,2784.0,9.9361,3.2405,1.0000,8.0000,10.0000,11.0000,29.0000

In [8]:
# quais as correlações entre as características numéricas?
data.corr()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
length,1.0000,0.9866,0.8896,0.9263,0.8987,0.9022,0.9029,0.5559
diameter,0.9866,1.0000,0.8962,0.9264,0.8947,0.8999,0.9095,0.5728
height,0.8896,0.8962,1.0000,0.8805,0.8318,0.8577,0.8821,0.5936
whole_weight,0.9263,0.9264,0.8805,1.0000,0.9699,0.9695,0.9565,0.5359
shucked_weight,0.8987,0.8947,0.8318,0.9699,1.0000,0.9347,0.8864,0.4188
viscera_weight,0.9022,0.8999,0.8577,0.9695,0.9347,1.0000,0.9137,0.5012
shell_weight,0.9029,0.9095,0.8821,0.9565,0.8864,0.9137,1.0000,0.6227
rings,0.5559,0.5728,0.5936,0.5359,0.4188,0.5012,0.6227,1.0000

In [9]:
# show variable correlation which is more than 0.6 (positive or negative)
corr = data.corr()
corr[corr != 1][abs(corr) > 0.6].dropna(how='all', axis=1).dropna(how='all', axis=0)

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
length,NaN,0.9866,0.8896,0.9263,0.8987,0.9022,0.9029,NaN
diameter,0.9866,NaN,0.8962,0.9264,0.8947,0.8999,0.9095,NaN
height,0.8896,0.8962,NaN,0.8805,0.8318,0.8577,0.8821,NaN
whole_weight,0.9263,0.9264,0.8805,NaN,0.9699,0.9695,0.9565,NaN
shucked_weight,0.8987,0.8947,0.8318,0.9699,NaN,0.9347,0.8864,NaN
viscera_weight,0.9022,0.8999,0.8577,0.9695,0.9347,NaN,0.9137,NaN
shell_weight,0.9029,0.9095,0.8821,0.9565,0.8864,0.9137,NaN,0.6227
rings,NaN,NaN,NaN,NaN,NaN,NaN,0.6227,NaN

In [10]:
data.groupby('rings').mean()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight
rings,,,,,,,
1,0.0750,0.0550,0.0100,0.0020,0.0010,0.0005,0.0015
3,0.1746,0.1283,0.0408,0.0287,0.0118,0.0060,0.0092
4,0.2231,0.1649,0.0537,0.0600,0.0252,0.0130,0.0183
5,0.2917,0.2151,0.0721,0.1342,0.0690,0.0291,0.0390
6,0.3649,0.2750,0.0904,0.2647,0.1193,0.0572,0.0770
7,0.4227,0.3222,0.1057,0.3972,0.1836,0.0853,0.1111
8,0.4973,0.3839,0.1272,0.6383,0.2922,0.1377,0.1781
9,0.5454,0.4234,0.1429,0.8489,0.3885,0.1873,0.2344
10,0.5689,0.4444,0.1526,0.9784,0.4314,0.2161,0.2753
11,0.5931,0.4659,0.1599,1.1121,0.4903,0.2444,0.3114
12,0.5907,0.4632,0.1607,1.1021,0.4755,0.2437,0.3173
13,0.5762,0.4530,0.1587,1.0615,0.4272,0.2326,0.3151
14,0.5763,0.4562,0.1643,1.0718,0.4280,0.2318,0.3272
15,0.5758,0.4564,0.1595,1.0135,0.3979,0.2209,0.3140
16,0.5884,0.4696,0.1690,1.1141,0.4230,0.2407,0.3606
17,0.6026,0.4731,0.1721,1.2202,0.4614,0.2536,0.3881
18,0.5846,0.4611,0.1716,1.1307,0.4176,0.2330,0.3542
19,0.5915,0.4702,0.1690,1.1404,0.4309,0.2424,0.3572
20,0.6047,0.4813,0.1727,1.2504,0.4534,0.2581,0.4302
21,0.6133,0.4842,0.1692,1.2103,0.4338,0.2370,0.4258
22,0.5687,0.4425,0.1762,0.9261,0.3085,0.1726,0.3013
23,0.6167,0.4875,0.1717,1.2790,0.4521,0.2793,0.3892
24,0.7000,0.5400,0.2150,1.9780,0.6675,0.3125,0.7100
25,0.6450,0.4900,0.2150,1.4060,0.4265,0.2285,0.5100
26,0.6000,0.4950,0.1950,1.0575,0.3840,0.1900,0.3750
27,0.6650,0.5350,0.2250,2.1835,0.7535,0.3910,0.8850
29,0.7000,0.5850,0.1850,1.8075,0.7055,0.3215,0.4750

In [11]:
numeric_feats = data.dtypes[data.dtypes != "object"].index
numeric_feats

Index(['length', 'diameter', 'height', 'whole_weight', 'shucked_weight',
       'viscera_weight', 'shell_weight', 'rings'],
      dtype='object')

from scipy.stats import skew
skewed_feats = data[numeric_feats].apply(lambda x: skew(x.dropna())) # compute skewness
skewed_feats = skewed_feats[skewed_feats > 0.75]
skewed_feats = skewed_feats.index
skewed_feats

In [12]:
data.head(10).T

id,2758,1384,1131,3726,3445,817,2742,3757,2609,2728
sex,M,F,M,I,I,I,I,I,F,I
length,0.535,0.63,0.565,0.5,0.495,0.35,0.46,0.52,0.63,0.405
diameter,0.43,0.485,0.435,0.395,0.4,0.27,0.345,0.41,0.495,0.31
height,0.155,0.17,0.15,0.145,0.145,0.09,0.105,0.14,0.2,0.11
whole_weight,0.7845,1.321,0.99,0.7865,0.578,0.2055,0.415,0.699,1.425,0.91
shucked_weight,0.3285,0.5945,0.5795,0.332,0.2545,0.075,0.187,0.3395,0.659,0.416
viscera_weight,0.169,0.345,0.1825,0.1815,0.1305,0.0575,0.087,0.129,0.336,0.2075
shell_weight,0.245,0.345,0.206,0.2455,0.1645,0.062,0.11,0.1945,0.38,0.0995
rings,10,9,8,8,8,6,8,10,11,8

data[skewed_feats] = np.log1p(data[skewed_feats])

data.head(10).T

data = pd.get_dummies(data)
data = data.fillna(data.mean())

In [13]:
data.isna().sum()

sex               0
length            0
diameter          0
height            0
whole_weight      0
shucked_weight    0
viscera_weight    0
shell_weight      0
rings             0
dtype: int64

In [14]:
data.sex.describe()

count     2784
unique       3
top          M
freq       992
Name: sex, dtype: object

In [15]:
data.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
id,,,,,,,,,
2758,M,0.535,0.430,0.155,0.784,0.329,0.169,0.245,10
1384,F,0.630,0.485,0.170,1.321,0.595,0.345,0.345,9
1131,M,0.565,0.435,0.150,0.990,0.580,0.182,0.206,8
3726,I,0.500,0.395,0.145,0.786,0.332,0.181,0.245,8
3445,I,0.495,0.400,0.145,0.578,0.255,0.131,0.165,8

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(data))

data_scaled = pd.DataFrame(scaler.transform(data), columns=data.columns, index=data.index)
data_scaled.head()