## Importação dos pacotes

In [1]:
# importar pacotes necessários
import numpy as np
import pandas as pd

In [2]:
# definir parâmetros extras
pd.set_option('precision', 3)
pd.set_option('display.max_columns', 100)

## Carga dos dados

In [3]:
# carregar arquivo de dados de treino
data = pd.read_csv('abalone-train.csv', index_col='id')

# mostrar alguns exemplos de registros
data.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
id,,,,,,,,,
2758,M,0.535,0.430,0.155,0.784,0.329,0.169,0.245,10
1384,F,0.630,0.485,0.170,1.321,0.595,0.345,0.345,9
1131,M,0.565,0.435,0.150,0.990,0.580,0.182,0.206,8
3726,I,0.500,0.395,0.145,0.786,0.332,0.181,0.245,8
3445,I,0.495,0.400,0.145,0.578,0.255,0.131,0.165,8

In [4]:
# quantas linhas e colunas existem?
data.shape

(2784, 9)

## Análise dos dados

In [5]:
# quais são as colunas e respectivos tipos de dados?
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2784 entries, 2758 to 852
Data columns (total 9 columns):
sex               2784 non-null object
length            2784 non-null float64
diameter          2784 non-null float64
height            2784 non-null float64
whole_weight      2784 non-null float64
shucked_weight    2784 non-null float64
viscera_weight    2784 non-null float64
shell_weight      2784 non-null float64
rings             2784 non-null int64
dtypes: float64(7), int64(1), object(1)
memory usage: 206.6+ KB

In [6]:
# existem colunas com dados nulos?
data[data.columns[data.isnull().any()]].isnull().sum()

Series([], dtype: float64)

In [7]:
# sumário estatístico das características numéricas
data.describe().T

                 count   mean    std        min    25%     50%     75%     max
length          2784.0  0.522  0.120  7.500e-02  0.450   0.540   0.610   0.815
diameter        2784.0  0.406  0.099  5.500e-02  0.345   0.420   0.480   0.650
height          2784.0  0.139  0.039  0.000e+00  0.110   0.140   0.165   0.515
whole_weight    2784.0  0.817  0.484  2.000e-03  0.435   0.785   1.136   2.780
shucked_weight  2784.0  0.355  0.219  1.000e-03  0.182   0.332   0.498   1.349
viscera_weight  2784.0  0.178  0.109  5.000e-04  0.091   0.168   0.247   0.760
shell_weight    2784.0  0.235  0.136  1.500e-03  0.126   0.230   0.322   0.885
rings           2784.0  9.936  3.241  1.000e+00  8.000  10.000  11.000  29.000

In [8]:
# quais as correlações entre as características numéricas?
data.corr()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
length,1.000,0.987,0.890,0.926,0.899,0.902,0.903,0.556
diameter,0.987,1.000,0.896,0.926,0.895,0.900,0.910,0.573
height,0.890,0.896,1.000,0.881,0.832,0.858,0.882,0.594
whole_weight,0.926,0.926,0.881,1.000,0.970,0.970,0.956,0.536
shucked_weight,0.899,0.895,0.832,0.970,1.000,0.935,0.886,0.419
viscera_weight,0.902,0.900,0.858,0.970,0.935,1.000,0.914,0.501
shell_weight,0.903,0.910,0.882,0.956,0.886,0.914,1.000,0.623
rings,0.556,0.573,0.594,0.536,0.419,0.501,0.623,1.000

In [9]:
# show variable correlation which is more than 0.6 (positive or negative)
corr = data.corr()
corr[corr != 1][abs(corr) > 0.6].dropna(how='all', axis=1).dropna(how='all', axis=0)

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
length,NaN,0.987,0.890,0.926,0.899,0.902,0.903,NaN
diameter,0.987,NaN,0.896,0.926,0.895,0.900,0.910,NaN
height,0.890,0.896,NaN,0.881,0.832,0.858,0.882,NaN
whole_weight,0.926,0.926,0.881,NaN,0.970,0.970,0.956,NaN
shucked_weight,0.899,0.895,0.832,0.970,NaN,0.935,0.886,NaN
viscera_weight,0.902,0.900,0.858,0.970,0.935,NaN,0.914,NaN
shell_weight,0.903,0.910,0.882,0.956,0.886,0.914,NaN,0.623
rings,NaN,NaN,NaN,NaN,NaN,NaN,0.623,NaN

In [10]:
data.groupby('rings').mean()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight
rings,,,,,,,
1,0.075,0.055,0.010,0.002,0.001,5.000e-04,0.002
3,0.175,0.128,0.041,0.029,0.012,6.042e-03,0.009
4,0.223,0.165,0.054,0.060,0.025,1.296e-02,0.018
5,0.292,0.215,0.072,0.134,0.069,2.911e-02,0.039
6,0.365,0.275,0.090,0.265,0.119,5.719e-02,0.077
7,0.423,0.322,0.106,0.397,0.184,8.532e-02,0.111
8,0.497,0.384,0.127,0.638,0.292,1.377e-01,0.178
9,0.545,0.423,0.143,0.849,0.389,1.873e-01,0.234
10,0.569,0.444,0.153,0.978,0.431,2.161e-01,0.275
11,0.593,0.466,0.160,1.112,0.490,2.444e-01,0.311
12,0.591,0.463,0.161,1.102,0.475,2.437e-01,0.317
13,0.576,0.453,0.159,1.062,0.427,2.326e-01,0.315
14,0.576,0.456,0.164,1.072,0.428,2.318e-01,0.327
15,0.576,0.456,0.159,1.014,0.398,2.209e-01,0.314
16,0.588,0.470,0.169,1.114,0.423,2.407e-01,0.361
17,0.603,0.473,0.172,1.220,0.461,2.536e-01,0.388
18,0.585,0.461,0.172,1.131,0.418,2.330e-01,0.354
19,0.591,0.470,0.169,1.140,0.431,2.424e-01,0.357
20,0.605,0.481,0.173,1.250,0.453,2.581e-01,0.430
21,0.613,0.484,0.169,1.210,0.434,2.370e-01,0.426
22,0.569,0.443,0.176,0.926,0.308,1.726e-01,0.301
23,0.617,0.487,0.172,1.279,0.452,2.793e-01,0.389
24,0.700,0.540,0.215,1.978,0.667,3.125e-01,0.710
25,0.645,0.490,0.215,1.406,0.426,2.285e-01,0.510
26,0.600,0.495,0.195,1.058,0.384,1.900e-01,0.375
27,0.665,0.535,0.225,2.183,0.753,3.910e-01,0.885
29,0.700,0.585,0.185,1.808,0.706,3.215e-01,0.475

In [11]:
numeric_feats = data.dtypes[data.dtypes != "object"].index
numeric_feats

Index(['length', 'diameter', 'height', 'whole_weight', 'shucked_weight',
       'viscera_weight', 'shell_weight', 'rings'],
      dtype='object')

from scipy.stats import skew
skewed_feats = data[numeric_feats].apply(lambda x: skew(x.dropna())) # compute skewness
skewed_feats = skewed_feats[skewed_feats > 0.75]
skewed_feats = skewed_feats.index
skewed_feats

In [13]:
data.head(10).T

id,2758,1384,1131,3726,3445,817,2742,3757,2609,2728
sex,M,F,M,I,I,I,I,I,F,I
length,0.535,0.63,0.565,0.5,0.495,0.35,0.46,0.52,0.63,0.405
diameter,0.43,0.485,0.435,0.395,0.4,0.27,0.345,0.41,0.495,0.31
height,0.155,0.17,0.15,0.145,0.145,0.09,0.105,0.14,0.2,0.11
whole_weight,0.784,1.32,0.99,0.786,0.578,0.205,0.415,0.699,1.43,0.91
shucked_weight,0.329,0.595,0.58,0.332,0.255,0.075,0.187,0.34,0.659,0.416
viscera_weight,0.169,0.345,0.182,0.181,0.131,0.0575,0.087,0.129,0.336,0.207
shell_weight,0.245,0.345,0.206,0.245,0.165,0.062,0.11,0.195,0.38,0.0995
rings,10,9,8,8,8,6,8,10,11,8

data[skewed_feats] = np.log1p(data[skewed_feats])

data.head(10).T

data = pd.get_dummies(data)
data = data.fillna(data.mean())

In [14]:
data.isna().sum()

sex               0
length            0
diameter          0
height            0
whole_weight      0
shucked_weight    0
viscera_weight    0
shell_weight      0
rings             0
dtype: int64

print(data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))

In [15]:
data.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
id,,,,,,,,,
2758,M,0.535,0.430,0.155,0.784,0.329,0.169,0.245,10
1384,F,0.630,0.485,0.170,1.321,0.595,0.345,0.345,9
1131,M,0.565,0.435,0.150,0.990,0.580,0.182,0.206,8
3726,I,0.500,0.395,0.145,0.786,0.332,0.181,0.245,8
3445,I,0.495,0.400,0.145,0.578,0.255,0.131,0.165,8

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(data))

data_scaled = pd.DataFrame(scaler.transform(data), columns=data.columns, index=data.index)
data_scaled.head()

ValueError: could not convert string to float: 'M'