In [115]:
import pandas as pd
import numpy as np

In [116]:
# definir par√¢metros extras
pd.set_option('precision', 4)
pd.set_option('display.max_columns', None)

In [117]:
# carregar dados
data = pd.read_csv('data/allyears2k_headers.csv', sep=',', encoding='ISO-8859-1')

# embaralhar dados
data = data.sample(frac=1)

# mostrar quantidade de linhas e colunas
print(data.shape)

# mostrar exemplos de dados
data.head()

(43978, 31)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,IsArrDelayed,IsDepDelayed
40108,2007,1,1,1,2021.0,2000,2212.0,2155,WN,149,N623SW,51.0,55.0,41.0,17.0,21.0,STL,SDF,254.0,3.0,7.0,0,NaN,0,2.0,0.0,0.0,0.0,15.0,YES,YES
43494,2008,1,3,4,910.0,915,923.0,935,WN,453,N232WN,73.0,80.0,58.0,-12.0,-5.0,PHX,SNA,338.0,4.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NO,NO
21603,1997,1,22,3,1422.0,1415,1614.0,1602,HP,2028,N311AW,112.0,107.0,93.0,12.0,7.0,DEN,PHX,602.0,7.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,YES
18691,1996,1,27,6,1125.0,1100,1337.0,1315,WN,1488,N359,72.0,75.0,61.0,22.0,25.0,BUR,PHX,369.0,5.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,YES
8022,1991,1,27,7,1703.0,1705,1931.0,1944,US,112,NaN,148.0,159.0,NaN,-13.0,-2.0,TPA,SYR,1104.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NO,NO

In [118]:
# renomear coluna √≠ndice
data.index.names = ['FlightRecord']

In [119]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43978 entries, 40108 to 1998
Data columns (total 31 columns):
Year                 43978 non-null int64
Month                43978 non-null int64
DayofMonth           43978 non-null int64
DayOfWeek            43978 non-null int64
DepTime              42892 non-null float64
CRSDepTime           43978 non-null int64
ArrTime              42783 non-null float64
CRSArrTime           43978 non-null int64
UniqueCarrier        43978 non-null object
FlightNum            43978 non-null int64
TailNum              27954 non-null object
ActualElapsedTime    42783 non-null float64
CRSElapsedTime       43965 non-null float64
AirTime              27329 non-null float64
ArrDelay             42783 non-null float64
DepDelay             42892 non-null float64
Origin               43978 non-null object
Dest                 43978 non-null object
Distance             43943 non-null float64
TaxiIn               27952 non-null float64
TaxiOut              27954 non-null float64
Cancelled            43978 non-null int64
CancellationCode     221 non-null object
Diverted             43978 non-null int64
CarrierDelay         8933 non-null float64
WeatherDelay         8933 non-null float64
NASDelay             8933 non-null float64
SecurityDelay        8933 non-null float64
LateAircraftDelay    8933 non-null float64
IsArrDelayed         43978 non-null object
IsDepDelayed         43978 non-null object
dtypes: float64(15), int64(9), object(7)
memory usage: 9.6+ MB

In [120]:
data.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,43978.0000,43978.0000,43978.0000,43978.0000,42892.0000,43978.0000,42783.0000,43978.0000,43978.0000,42783.0000,43965.0000,27329.0000,42783.0000,42892.0000,43943.0000,27952.0000,27954.0000,43978.0000,43978.0000,8933.0000,8933.0000,8933.0000,8933.0000,8933.0000
mean,1997.5000,1.4091,14.6011,3.8206,1345.8467,1313.2229,1504.6341,1485.2892,818.8430,124.8145,125.0216,114.3161,9.3171,10.0074,730.1822,5.3814,14.1686,0.0247,0.0025,4.0478,0.2894,4.8550,0.0170,7.6201
std,6.3444,1.8747,9.1758,1.9050,465.3409,476.2511,484.3475,492.7504,777.4044,73.9744,73.4016,69.6363,29.8402,26.4388,578.4380,4.2020,9.9051,0.1552,0.0497,16.2057,4.4168,18.6198,0.4039,23.4876
min,1987.0000,1.0000,1.0000,1.0000,1.0000,0.0000,1.0000,0.0000,1.0000,16.0000,17.0000,14.0000,-63.0000,-16.0000,11.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,1992.0000,1.0000,6.0000,2.0000,929.0000,910.0000,1118.0000,1109.0000,204.0000,71.0000,71.0000,61.0000,-6.0000,-2.0000,326.0000,3.0000,9.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,1997.5000,1.0000,14.0000,4.0000,1330.0000,1320.0000,1527.0000,1516.0000,557.0000,101.0000,102.0000,91.0000,2.0000,1.0000,541.0000,5.0000,12.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,2003.0000,1.0000,23.0000,5.0000,1735.0000,1720.0000,1917.0000,1903.0000,1242.0000,151.0000,151.0000,140.0000,14.0000,10.0000,920.0000,6.0000,16.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
max,2008.0000,10.0000,31.0000,7.0000,2400.0000,2359.0000,2400.0000,2359.0000,3949.0000,475.0000,437.0000,402.0000,475.0000,473.0000,3365.0000,128.0000,254.0000,1.0000,1.0000,369.0000,201.0000,323.0000,14.0000,373.0000

In [121]:
data.describe(include=['O'])

,UniqueCarrier,TailNum,Origin,Dest,CancellationCode,IsArrDelayed,IsDepDelayed
count,43978,27954,43978,43978,221,43978,43978
unique,10,3500,132,134,3,2,2
top,US,UNKNOW,DEN,PHX,B,YES,YES
freq,18729,179,3558,9317,93,24441,23091

# converter campos float para int
cols = data.dtypes[data.dtypes == 'float'].index
cols = ['DepTime', 'ArrTime', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime',
       'ArrDelay', 'DepDelay', 'Distance', 'TaxiIn', 'TaxiOut', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']
data[cols].info()
#data[cols] = data[cols].astype(int)
#data[cols].head()

In [122]:
# criar coluna √∫nica com informa√ß√£o da data
data['FlightDate'] = pd.to_datetime(data[['Year', 'Month', 'DayofMonth']].rename(columns={'DayofMonth': 'Day'}))

In [123]:
# remover colunas derivadas da data
data.drop(['Year', 'Month', 'DayofMonth', 'DayOfWeek'], axis=1, inplace=True)

In [124]:
# arrumar ordem das colunas
cols = data.columns.values[:-1].tolist()
cols.insert(0, 'FlightDate')
data = data[cols]

data.head()

data.info()

In [125]:
# dividir os dados de treino e teste
divisao = int(data.shape[0] * 4 / 5)
train = data[:divisao]
test = data[divisao:]
print(train.shape, test.shape)

(35182, 28) (8796, 28)

In [126]:
train.head()

,FlightDate,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,IsArrDelayed,IsDepDelayed
FlightRecord,,,,,,,,,,,,,,,,,,,,,,,,,,,,
40108,2007-01-01,2021.0,2000,2212.0,2155,WN,149,N623SW,51.0,55.0,41.0,17.0,21.0,STL,SDF,254.0,3.0,7.0,0,NaN,0,2.0,0.0,0.0,0.0,15.0,YES,YES
43494,2008-01-03,910.0,915,923.0,935,WN,453,N232WN,73.0,80.0,58.0,-12.0,-5.0,PHX,SNA,338.0,4.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NO,NO
21603,1997-01-22,1422.0,1415,1614.0,1602,HP,2028,N311AW,112.0,107.0,93.0,12.0,7.0,DEN,PHX,602.0,7.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,YES
18691,1996-01-27,1125.0,1100,1337.0,1315,WN,1488,N359,72.0,75.0,61.0,22.0,25.0,BUR,PHX,369.0,5.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,YES
8022,1991-01-27,1703.0,1705,1931.0,1944,US,112,NaN,148.0,159.0,NaN,-13.0,-2.0,TPA,SYR,1104.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NO,NO

In [127]:
test.head()

,FlightDate,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,IsArrDelayed,IsDepDelayed
FlightRecord,,,,,,,,,,,,,,,,,,,,,,,,,,,,
24620,1999-01-16,1056.0,1055,1338.0,1344,AA,1020,N710AA,222.0,229.0,201.0,-6.0,1.0,SJU,PHL,1576.0,3.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NO,YES
25358,1999-01-04,902.0,902,1034.0,1025,HP,191,N311AW,92.0,83.0,72.0,9.0,0.0,ABQ,PHX,328.0,14.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,NO
7917,1990-01-16,1001.0,1000,1114.0,1117,US,58,NaN,73.0,77.0,NaN,-3.0,1.0,SFO,PSP,421.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NO,YES
10685,1992-01-19,1254.0,1240,1415.0,1406,US,65,NaN,141.0,146.0,NaN,9.0,14.0,PIT,MCI,773.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,YES
26646,2000-01-23,648.0,651,910.0,908,HP,2433,N305AW,82.0,77.0,61.0,2.0,-3.0,BUR,PHX,369.0,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,YES,NO

In [128]:
example = test[['IsDepDelayed']]
example['IsDepDelayed'] = example.index.map(lambda x: 'NO' if (x % 2 == 0) else 'YES')
example.head()

/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

             IsDepDelayed
FlightRecord
24620                  NO
25358                  NO
7917                  YES
10685                 YES
26646                  NO

In [129]:
example.describe()

       IsDepDelayed
count          8796
unique            2
top              NO
freq           4403

In [130]:
# gerar arquivos CSV
train.to_csv('airlines-train.csv')
test.drop(['IsDepDelayed'], axis=1).to_csv('airlines-test.csv')
test[['IsDepDelayed']].to_csv('airlines-solution.csv')
example.to_csv('airlines-example.csv')

In [131]:
!head airlines-*.csv

==> airlines-example.csv <==
FlightRecord,IsDepDelayed
24620,NO
25358,NO
7917,YES
10685,YES
26646,NO
35889,YES
7578,NO
8630,NO
4287,YES

==> airlines-solution.csv <==
FlightRecord,IsDepDelayed
24620,YES
25358,NO
7917,YES
10685,YES
26646,NO
35889,YES
7578,YES
8630,YES
4287,YES

==> airlines-test.csv <==
FlightRecord,FlightDate,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,IsArrDelayed
24620,1999-01-16,1056.0,1055,1338.0,1344,AA,1020,N710AA,222.0,229.0,201.0,-6.0,1.0,SJU,PHL,1576.0,3.0,18.0,0,,0,,,,,,NO
25358,1999-01-04,902.0,902,1034.0,1025,HP,191,N311AW,92.0,83.0,72.0,9.0,0.0,ABQ,PHX,328.0,14.0,6.0,0,,0,,,,,,YES
7917,1990-01-16,1001.0,1000,1114.0,1117,US,58,,73.0,77.0,,-3.0,1.0,SFO,PSP,421.0,,,0,,0,,,,,,NO
10685,1992-01-19,1254.0,1240,1415.0,1406,US,65,,141.0,146.0,,9.0,14.0,PIT,MCI,773.0,,,0,,0,,,,,,YES
26646,2000-01-23,648.0,651,910.0,908,HP,2433,N305AW,82.0,77.0,61.0,2.0,-3.0,BUR,PHX,369.0,4.0,17.0,0,,0,,,,,,YES
35889,2004-01-05,1057.0,1020,1547.0,1512,UA,510,N951UA,170.0,172.0,139.0,35.0,37.0,DEN,ATL,1199.0,14.0,17.0,0,,0,13.0,0.0,0.0,0.0,22.0,YES
7578,1990-01-27,1545.0,1540,1619.0,1617,US,55,,34.0,37.0,,2.0,5.0,LAX,SAN,109.0,,,0,,0,,,,,,YES
8630,1991-01-29,1339.0,1320,1445.0,1416,US,125,,66.0,56.0,,29.0,19.0,PIT,AVP,243.0,,,0,,0,,,,,,YES
4287,1989-01-12,1339.0,1325,2020.0,2005,UA,188,,281.0,280.0,,15.0,14.0,OGG,SFO,2338.0,,,0,,0,,,,,,YES

==> airlines-train.csv <==
FlightRecord,FlightDate,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,IsArrDelayed,IsDepDelayed
40108,2007-01-01,2021.0,2000,2212.0,2155,WN,149,N623SW,51.0,55.0,41.0,17.0,21.0,STL,SDF,254.0,3.0,7.0,0,,0,2.0,0.0,0.0,0.0,15.0,YES,YES
43494,2008-01-03,910.0,915,923.0,935,WN,453,N232WN,73.0,80.0,58.0,-12.0,-5.0,PHX,SNA,338.0,4.0,11.0,0,,0,,,,,,NO,NO
21603,1997-01-22,1422.0,1415,1614.0,1602,HP,2028,N311AW,112.0,107.0,93.0,12.0,7.0,DEN,PHX,602.0,7.0,12.0,0,,0,,,,,,YES,YES
18691,1996-01-27,1125.0,1100,1337.0,1315,WN,1488,N359,72.0,75.0,61.0,22.0,25.0,BUR,PHX,369.0,5.0,6.0,0,,0,,,,,,YES,YES
8022,1991-01-27,1703.0,1705,1931.0,1944,US,112,,148.0,159.0,,-13.0,-2.0,TPA,SYR,1104.0,,,0,,0,,,,,,NO,NO
19482,1996-01-24,1717.0,1712,1902.0,1857,UA,439,N7259U,105.0,105.0,85.0,5.0,5.0,DEN,PHX,602.0,4.0,16.0,0,,0,,,,,,YES,YES
14261,1994-01-25,1408.0,1410,1442.0,1454,US,233,,34.0,44.0,,-12.0,-2.0,CLT,FAY,118.0,,,0,,0,,,,,,NO,NO
18633,1996-01-27,1519.0,1510,1728.0,1725,WN,506,N305,69.0,75.0,54.0,3.0,9.0,BUR,PHX,369.0,3.0,12.0,0,,0,,,,,,YES,YES
20981,1997-01-08,1745.0,1745,2005.0,2000,WN,1014,N634,80.0,75.0,60.0,5.0,0.0,BUR,PHX,369.0,5.0,15.0,0,,0,,,,,,YES,NO