## Importação dos pacotes

In [1]:
# importar pacotes necessários
import numpy as np
import pandas as pd

In [2]:
# definir parâmetros extras
pd.set_option('precision', 3)
pd.set_option('display.max_columns', 100)

## Carga dos dados

In [3]:
# carregar arquivo de dados de treino
data = pd.read_csv('wine-train.csv', index_col='wine')

# mostrar alguns exemplos de registros
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.997,3.04,0.53,8.9,bad
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.993,3.24,0.46,10.4,good
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.998,3.23,0.48,9.1,bad
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.996,3.15,0.46,10.9,bad
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.995,3.13,0.59,10.5,bad

In [4]:
# quantas linhas e colunas existem?
data.shape

(3265, 12)

## Análise dos dados

In [5]:
# quais são as colunas e respectivos tipos de dados?
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3265 entries, 4783 to 2658
Data columns (total 12 columns):
fixed_acidity           3265 non-null float64
volatile_acidity        3265 non-null float64
citric_acid             3265 non-null float64
residual_sugar          3265 non-null float64
chlorides               3265 non-null float64
free_sulfur_dioxide     3265 non-null float64
total_sulfur_dioxide    3265 non-null float64
density                 3265 non-null float64
ph                      3265 non-null float64
sulphates               3265 non-null float64
alcohol                 3265 non-null float64
quality                 3265 non-null object
dtypes: float64(11), object(1)
memory usage: 318.8+ KB

In [6]:
# existem colunas com dados nulos?
data[data.columns[data.isnull().any()]].isnull().sum()

Series([], dtype: float64)

In [7]:
# sumário estatístico das características numéricas
data.describe().T

,count,mean,std,min,25%,50%,75%,max
fixed_acidity,3265.0,6.857,0.857,3.900,6.300,6.800,7.300,11.800
volatile_acidity,3265.0,0.278,0.101,0.080,0.210,0.260,0.320,1.005
citric_acid,3265.0,0.334,0.123,0.000,0.260,0.320,0.390,1.230
residual_sugar,3265.0,6.442,5.093,0.600,1.700,5.300,9.900,65.800
chlorides,3265.0,0.045,0.021,0.009,0.036,0.043,0.050,0.290
free_sulfur_dioxide,3265.0,35.447,17.321,2.000,23.000,34.000,46.000,289.000
total_sulfur_dioxide,3265.0,138.221,42.324,9.000,108.000,134.000,167.000,440.000
density,3265.0,0.994,0.003,0.987,0.992,0.994,0.996,1.039
ph,3265.0,3.186,0.151,2.740,3.080,3.180,3.280,3.820
sulphates,3265.0,0.489,0.114,0.220,0.410,0.470,0.550,1.080
alcohol,3265.0,10.520,1.231,8.000,9.500,10.400,11.400,14.050

In [8]:
# quais as correlações entre as características numéricas?
data.corr()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol
fixed_acidity,1.000,-0.013,0.293,0.099,0.010,-4.997e-02,0.080,0.269,-4.382e-01,-0.016,-0.112
volatile_acidity,-0.013,1.000,-0.152,0.070,0.051,-9.582e-02,0.077,0.030,-1.996e-02,-0.036,0.090
citric_acid,0.293,-0.152,1.000,0.097,0.146,8.185e-02,0.116,0.158,-1.710e-01,0.058,-0.085
residual_sugar,0.099,0.070,0.097,1.000,0.073,2.729e-01,0.379,0.836,-1.979e-01,-0.021,-0.425
chlorides,0.010,0.051,0.146,0.073,1.000,9.208e-02,0.192,0.252,-8.321e-02,0.012,-0.378
free_sulfur_dioxide,-0.050,-0.096,0.082,0.273,0.092,1.000e+00,0.627,0.275,6.917e-04,0.045,-0.247
total_sulfur_dioxide,0.080,0.077,0.116,0.379,0.192,6.270e-01,1.000,0.513,2.462e-02,0.123,-0.442
density,0.269,0.030,0.158,0.836,0.252,2.747e-01,0.513,1.000,-9.447e-02,0.076,-0.760
ph,-0.438,-0.020,-0.171,-0.198,-0.083,6.917e-04,0.025,-0.094,1.000e+00,0.148,0.119
sulphates,-0.016,-0.036,0.058,-0.021,0.012,4.539e-02,0.123,0.076,1.482e-01,1.000,-0.013
alcohol,-0.112,0.090,-0.085,-0.425,-0.378,-2.468e-01,-0.442,-0.760,1.185e-01,-0.013,1.000

In [9]:
# show variable correlation which is more than 0.6 (positive or negative)
corr = data.corr()
corr[corr != 1][abs(corr) > 0.6].dropna(how='all', axis=1).dropna(how='all', axis=0)

,residual_sugar,free_sulfur_dioxide,total_sulfur_dioxide,density,alcohol
residual_sugar,NaN,NaN,NaN,0.836,NaN
free_sulfur_dioxide,NaN,NaN,0.627,NaN,NaN
total_sulfur_dioxide,NaN,0.627,NaN,NaN,NaN
density,0.836,NaN,NaN,NaN,-0.76
alcohol,NaN,NaN,NaN,-0.760,NaN

In [10]:
data.groupby('quality').mean()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol
quality,,,,,,,,,,,
bad,6.889,0.281,0.337,6.724,0.048,35.795,141.800,0.994,3.179,0.486,10.263
good,6.742,0.267,0.325,5.422,0.038,34.192,125.316,0.992,3.209,0.498,11.445

In [11]:
numeric_feats = data.dtypes[data.dtypes != "object"].index
numeric_feats

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'ph', 'sulphates', 'alcohol'],
      dtype='object')

In [12]:
from scipy.stats import skew
skewed_feats = data[numeric_feats].apply(lambda x: skew(x.dropna())) # compute skewness
skewed_feats = skewed_feats[skewed_feats > 0.75]
skewed_feats = skewed_feats.index
skewed_feats

Index(['volatile_acidity', 'citric_acid', 'residual_sugar', 'chlorides',
       'density', 'sulphates'],
      dtype='object')

In [13]:
data.head(10).T

wine,1942,3847,3183,2745,2977,1421,1709,4601,2326,2922
fixed_acidity,8.300,6.400,6.500,6.700,6.600,6.200,6.800,6.900,6.900,6.500
volatile_acidity,0.360,0.320,0.240,0.440,0.230,0.180,0.220,0.230,0.350,0.440
citric_acid,0.570,0.230,0.380,0.220,0.200,0.490,0.300,0.350,0.550,0.470
residual_sugar,15.000,16.200,1.000,4.300,11.400,4.500,13.600,6.900,11.950,5.450
chlorides,0.052,0.055,0.027,0.032,0.044,0.047,0.055,0.030,0.038,0.014
free_sulfur_dioxide,35.000,36.000,31.000,19.000,45.000,17.000,50.000,45.000,22.000,44.000
total_sulfur_dioxide,256.000,176.000,90.000,99.000,131.000,90.000,180.000,116.000,111.000,137.000
density,1.000,0.999,0.989,0.990,0.996,0.992,0.998,0.992,0.997,0.990
ph,2.930,3.260,3.240,3.260,2.960,3.270,3.440,2.800,3.110,3.130
sulphates,0.640,0.540,0.360,0.530,0.510,0.370,0.390,0.540,0.290,0.320
alcohol,8.600,9.100,12.300,12.800,9.700,11.600,9.800,11.000,9.700,13.000
quality,5.000,5.000,6.000,7.000,6.000,6.000,5.000,6.000,5.000,8.000

data[skewed_feats] = np.log1p(data[skewed_feats])

data.head(10).T

data = pd.get_dummies(data)
data = data.fillna(data.mean())

In [14]:
data.isna().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
ph                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

# carregar arquivo de dados de treino (normalizados)
data = pd.read_csv('wine-train-scaled.csv', index_col='wine')

In [27]:
# https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba

Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

print(IQR)

'''
print('')
print(data.mean())
print('')
print(data.std())
'''

fixed_acidity           0.097
volatile_acidity        0.124
citric_acid             0.072
residual_sugar          0.125
chlorides               0.048
free_sulfur_dioxide     0.161
total_sulfur_dioxide    0.197
density                 0.085
ph                      0.182
sulphates               0.163
alcohol                 0.333
quality                 0.167
dtype: float64

"\nprint('')\nprint(data.mean())\nprint('')\nprint(data.std())\n"

print(data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))

In [32]:
# https://www.kdnuggets.com/2017/02/removing-outliers-standard-deviation-python.html

#TODO: remover outliers para cada valor de "quality" (de 3 a 9)

spread = 3

removed_ids = ((data < (Q1 - spread * IQR)) | (data > (Q3 + spread * IQR))).index.values
print('removed ids:', removed_ids)

data_out = data[~((data < (Q1 - spread * IQR)) | (data > (Q3 + spread * IQR))).any(axis=1)]
#data_out = data[~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)]

print('before:', data.shape, '=> after:', data_out.shape,
      ':: removed %d lines' % int(data.shape[0] - data_out.shape[0]))

removed ids: [1942 3847 3183 ...  895  563 4334]
before: (3265, 12) => after: (3130, 12) :: removed 135 lines

In [33]:
data_out.head(10).T

wine,1942,3847,3183,2745,2977,1421,1709,4601,2326,2922
fixed_acidity,0.427,0.243,0.252,0.272,0.262,0.223,0.282,0.291,0.291,0.252
volatile_acidity,0.316,0.271,0.181,0.407,0.169,0.113,0.158,0.169,0.305,0.407
citric_acid,0.343,0.139,0.229,0.133,0.120,0.295,0.181,0.211,0.331,0.283
residual_sugar,0.221,0.239,0.006,0.057,0.166,0.060,0.199,0.097,0.174,0.074
chlorides,0.147,0.158,0.062,0.079,0.120,0.130,0.158,0.072,0.099,0.017
free_sulfur_dioxide,0.242,0.249,0.212,0.125,0.315,0.110,0.352,0.315,0.147,0.308
total_sulfur_dioxide,0.812,0.549,0.266,0.296,0.401,0.266,0.562,0.352,0.336,0.421
density,0.250,0.222,0.041,0.059,0.172,0.092,0.218,0.103,0.188,0.053
ph,0.191,0.491,0.473,0.491,0.218,0.500,0.655,0.073,0.355,0.373
sulphates,0.488,0.372,0.163,0.360,0.337,0.174,0.198,0.372,0.081,0.116
alcohol,0.100,0.183,0.717,0.800,0.283,0.600,0.300,0.500,0.283,0.833
quality,0.333,0.333,0.500,0.667,0.500,0.500,0.333,0.500,0.333,0.833

data_out.to_csv('wine-train-without-outliers.csv')

In [168]:
spread = 0.5

data['outlier'] = False

for quality in np.arange(3, 10):
#if (True):

    #quality = 5
    dtqu = data[data.quality == quality]
    
    Q1 = dtqu.quantile(0.25)
    Q3 = dtqu.quantile(0.75)
    IQR = Q3 - Q1
    
    removed_ids = ~((dtqu < (Q1 - spread * IQR)) | (dtqu > (Q3 + spread * IQR))).any(axis=1)
    df_rids = pd.DataFrame(data=removed_ids, columns=['outlier'])
    
    data.update(df_rids)
    
    #print(quality, dtqu[dtqu.outlier == True].count())
    print(quality, data[data.outlier == False].shape[0])

3 3263
4 3240
5 3042
6 2754
7 2626
8 2592
9 2592

In [164]:
removed_ids.head()

wine
827    False
876    False
dtype: bool

In [165]:
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality,outlier
wine,,,,,,,,,,,,,
1942,8.3,0.36,0.57,15.0,0.052,35.0,256.0,1.000,2.93,0.64,8.6,5.0,False
3847,6.4,0.32,0.23,16.2,0.055,36.0,176.0,0.999,3.26,0.54,9.1,5.0,True
3183,6.5,0.24,0.38,1.0,0.027,31.0,90.0,0.989,3.24,0.36,12.3,6.0,False
2745,6.7,0.44,0.22,4.3,0.032,19.0,99.0,0.990,3.26,0.53,12.8,7.0,False
2977,6.6,0.23,0.20,11.4,0.044,45.0,131.0,0.996,2.96,0.51,9.7,6.0,False

In [166]:
data[['ph','outlier']].groupby('outlier').count()

           ph
outlier
False    2592
True      673

In [167]:
data[data.outlier == False].shape
#data_out.shape

(2592, 13)

In [169]:
data[data.outlier == False].to_csv('wine-train-without-outliers.csv')

In [39]:
data_out.head()

Empty DataFrame
Columns: [fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, ph, sulphates, alcohol, quality]
Index: []

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(data))

data_scaled = pd.DataFrame(scaler.transform(data), columns=data.columns, index=data.index)
data_scaled.head()

MinMaxScaler(copy=True, feature_range=(0, 1))

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
1942,0.427,0.316,0.343,0.221,0.147,0.242,0.812,0.250,0.191,0.488,0.100,0.333
3847,0.243,0.271,0.139,0.239,0.158,0.249,0.549,0.222,0.491,0.372,0.183,0.333
3183,0.252,0.181,0.229,0.006,0.062,0.212,0.266,0.041,0.473,0.163,0.717,0.500
2745,0.272,0.407,0.133,0.057,0.079,0.125,0.296,0.059,0.491,0.360,0.800,0.667
2977,0.262,0.169,0.120,0.166,0.120,0.315,0.401,0.172,0.218,0.337,0.283,0.500

In [24]:
data_scaled.to_csv('wine-train-scaled.csv')