In [1]:
import pandas as pd
import numpy as np

In [2]:
# carregar dados
data = pd.read_csv('data/winequality-white.csv', sep=';')

# embaralhar dados
data = data.sample(frac=1)

# mostrar quantidade de linhas e colunas
print(data.shape)

# mostrar exemplos de dados
data.head()

(4898, 12)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2169,7.4,0.19,0.30,12.8,0.053,48.5,229.0,0.99860,3.14,0.49,9.1,7
1382,6.6,0.56,0.16,3.1,0.045,28.0,92.0,0.99400,3.12,0.35,9.1,6
3346,6.7,0.18,0.24,10.3,0.057,64.0,185.0,0.99519,3.12,0.50,10.6,6
3308,6.4,0.35,0.28,12.6,0.039,19.0,124.0,0.99539,3.20,0.43,10.6,6
3167,5.6,0.28,0.40,6.1,0.034,36.0,118.0,0.99144,3.21,0.43,12.1,7

In [3]:
# renomear coluna índice
data.index.names = ['wine']

In [4]:
# modificar nomes das colunas

cols = {}
for col in data.columns:
    newcol = col.lower().replace(' ', '_')
    cols[col] = newcol
    #print(col, '=>', newcol)

#print(type(cols), cols)

data.rename(columns=cols, inplace=True)

# aumentar a precisão da coluna alvo
data.quality = round(data.quality + 1e-3, 2)

In [5]:
data.quality = data.quality.map(lambda x: 'good' if x > 6 else 'bad')

In [6]:
data['quality'].describe()

count     4898
unique       2
top        bad
freq      3838
Name: quality, dtype: object

In [7]:
# exibir dados
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
2169,7.4,0.19,0.30,12.8,0.053,48.5,229.0,0.99860,3.14,0.49,9.1,good
1382,6.6,0.56,0.16,3.1,0.045,28.0,92.0,0.99400,3.12,0.35,9.1,bad
3346,6.7,0.18,0.24,10.3,0.057,64.0,185.0,0.99519,3.12,0.50,10.6,bad
3308,6.4,0.35,0.28,12.6,0.039,19.0,124.0,0.99539,3.20,0.43,10.6,bad
3167,5.6,0.28,0.40,6.1,0.034,36.0,118.0,0.99144,3.21,0.43,12.1,good

In [8]:
# dividir os dados de treino e teste

divisao = int(data.shape[0] * 2 / 3)

train = data[:divisao]
test = data[divisao:]

print(train.shape, test.shape)

(3265, 12) (1633, 12)

In [9]:
train.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
2169,7.4,0.19,0.30,12.8,0.053,48.5,229.0,0.99860,3.14,0.49,9.1,good
1382,6.6,0.56,0.16,3.1,0.045,28.0,92.0,0.99400,3.12,0.35,9.1,bad
3346,6.7,0.18,0.24,10.3,0.057,64.0,185.0,0.99519,3.12,0.50,10.6,bad
3308,6.4,0.35,0.28,12.6,0.039,19.0,124.0,0.99539,3.20,0.43,10.6,bad
3167,5.6,0.28,0.40,6.1,0.034,36.0,118.0,0.99144,3.21,0.43,12.1,good

In [10]:
test.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
1271,8.1,0.50,0.47,1.1,0.037,23.0,126.0,0.99380,3.21,0.42,10.9,bad
1945,8.1,0.26,0.30,7.8,0.049,39.0,152.0,0.99540,2.99,0.58,10.0,bad
4235,6.4,0.29,0.18,15.0,0.040,21.0,116.0,0.99736,3.14,0.50,9.2,bad
4779,6.0,0.59,0.00,0.8,0.037,30.0,95.0,0.99032,3.10,0.40,10.9,bad
3502,6.7,0.29,0.45,14.3,0.054,30.0,181.0,0.99869,3.14,0.57,9.1,bad

In [11]:
example = test[['quality']]
#example['quality'] = example.index.map(lambda x: float(x % 7 + 3))
example['quality'] = example.index.map(lambda x: 'good' if (x % 2 == 0) else 'bad')
example.head()

/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

     quality
wine
1271     bad
1945     bad
4235     bad
4779     bad
3502    good

In [12]:
example.describe()

       quality
count     1633
unique       2
top       good
freq       838

In [13]:
train.to_csv('wine-train.csv')

test.drop(['quality'], axis=1).to_csv('wine-test.csv')
test[['quality']].to_csv('wine-solution.csv')

example.to_csv('wine-example.csv')

In [14]:
!head wine-*.csv

==> wine-example.csv <==
wine,quality
1271,bad
1945,bad
4235,bad
4779,bad
3502,good
4030,good
649,bad
963,bad
4514,good

==> wine-solution.csv <==
wine,quality
1271,bad
1945,bad
4235,bad
4779,bad
3502,bad
4030,bad
649,good
963,bad
4514,bad

==> wine-test.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol
1271,8.1,0.5,0.47,1.1,0.037,23.0,126.0,0.9938,3.21,0.42,10.9
1945,8.1,0.26,0.3,7.8,0.049,39.0,152.0,0.9954,2.99,0.58,10.0
4235,6.4,0.29,0.18,15.0,0.04,21.0,116.0,0.99736,3.14,0.5,9.2
4779,6.0,0.59,0.0,0.8,0.037,30.0,95.0,0.99032,3.1,0.4,10.9
3502,6.7,0.29,0.45,14.3,0.054,30.0,181.0,0.99869,3.14,0.57,9.1
4030,6.9,0.19,0.38,1.15,0.023,30.0,105.0,0.99047,3.11,0.38,11.4
649,7.1,0.26,0.34,14.4,0.067,35.0,189.0,0.9986,3.07,0.53,9.1
963,6.1,0.19,0.25,4.0,0.023,23.0,112.0,0.9923,3.37,0.51,11.6
4514,6.1,0.4,0.18,9.0,0.051,28.5,259.0,0.9964,3.19,0.5,8.8

==> wine-train-filtered-scaled.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
3472,0.25,0.0784313725490196,0.21686746987951808,0.02147239263803681,0.10682492581602374,0.07665505226480837,0.2813953488372093,0.1101253616200566,0.5047619047619047,0.42352941176470577,0.403225806451613,0.0
3455,0.30999999999999994,0.14705882352941177,0.14457831325301204,0.004601226993865032,0.06528189910979229,0.09407665505226481,0.17674418604651165,0.041080038572808064,0.12380952380952381,0.17647058823529405,0.6774193548387097,0.0
3322,0.15000000000000002,0.1764705882352941,0.18072289156626506,0.018404907975460124,0.08902077151335314,0.0975609756097561,0.22093023255813954,0.05438765670202628,0.6761904761904765,0.34117647058823525,0.7258064516129035,1.0
4896,0.13,0.20588235294117646,0.18072289156626506,0.007668711656441719,0.03857566765578636,0.0627177700348432,0.23255813953488375,0.030086788813886045,0.5428571428571427,0.17647058823529405,0.774193548387097,1.0
2123,0.26,0.16666666666666666,0.16265060240963858,0.1549079754601227,0.19881305637982197,0.156794425087108,0.33488372093023255,0.18457087753133905,0.2666666666666666,0.17647058823529405,0.16129032258064524,0.0
4678,0.24,0.2009803921568627,0.29518072289156627,0.16564417177914112,0.07715133531157273,0.1916376306620209,0.29534883720930233,0.19652844744454967,0.2952380952380955,0.36470588235294116,0.14516129032258074,0.0
3159,0.27,0.10784313725490197,0.1927710843373494,0.11196319018404909,0.09792284866468845,0.0975609756097561,0.27906976744186046,0.14329797492767682,0.6000000000000001,0.188235294117647,0.403225806451613,0.0
3664,0.07999999999999996,0.20588235294117646,0.32530120481927716,0.07822085889570553,0.07715133531157273,0.18118466898954705,0.3372093023255814,0.05072324011571894,0.4761904761904763,0.12941176470588234,0.7903225806451615,1.0
2025,0.32999999999999996,0.21568627450980388,0.42771084337349397,0.010736196319018405,0.4480712166172108,0.14634146341463414,0.3232558139534884,0.14792671166827276,0.2952380952380955,0.2235294117647058,0.14516129032258074,0.0

==> wine-train-without-outliers.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
3472,6.7,0.16,0.36,2.0,0.045,24.0,131.0,0.99284,3.3,0.59,10.5,bad
3455,7.3,0.23,0.24,0.9,0.031,29.0,86.0,0.98926,2.9,0.38,12.2,bad
3322,5.7,0.26,0.3,1.8,0.039,30.0,105.0,0.98995,3.48,0.52,12.5,good
4896,5.5,0.29,0.3,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,good
2123,6.8,0.25,0.27,10.7,0.076,47.0,154.0,0.9967,3.05,0.38,9.0,bad
4678,6.6,0.285,0.49,11.4,0.035,57.0,137.0,0.99732,3.08,0.54,8.9,bad
3159,6.9,0.19,0.32,7.9,0.042,30.0,130.0,0.99456,3.4,0.39,10.5,bad
3664,5.0,0.29,0.54,5.7,0.035,54.0,155.0,0.98976,3.27,0.34,12.9,good
2025,7.5,0.3,0.71,1.3,0.16,44.0,149.0,0.9948,3.08,0.42,8.9,bad

==> wine-train.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
2169,7.4,0.19,0.3,12.8,0.053,48.5,229.0,0.9986,3.14,0.49,9.1,good
1382,6.6,0.56,0.16,3.1,0.045,28.0,92.0,0.994,3.12,0.35,9.1,bad
3346,6.7,0.18,0.24,10.3,0.057,64.0,185.0,0.99519,3.12,0.5,10.6,bad
3308,6.4,0.35,0.28,12.6,0.039,19.0,124.0,0.99539,3.2,0.43,10.6,bad
3167,5.6,0.28,0.4,6.1,0.034,36.0,118.0,0.99144,3.21,0.43,12.1,good
1777,6.5,0.18,0.26,1.4,0.041,40.0,141.0,0.9941,3.34,0.72,9.5,bad
4721,6.1,0.32,0.33,10.7,0.036,27.0,98.0,0.99521,3.34,0.52,10.2,bad
3755,7.8,0.19,0.32,7.4,0.015,47.0,124.0,0.99278,2.99,0.39,11.0,bad
4688,6.7,0.16,0.32,12.5,0.035,18.0,156.0,0.99666,2.88,0.36,9.0,bad