In [1]:
import pandas as pd
import numpy as np

In [2]:
# carregar dados
data = pd.read_csv('winequality-white.csv', sep=';')

# embaralhar dados
data = data.sample(frac=1)

# mostrar quantidade de linhas e colunas
print(data.shape)

# mostrar exemplos de dados
data.head()

(4898, 12)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.99740,3.04,0.53,8.9,6
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.99347,3.24,0.46,10.4,8
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.99750,3.23,0.48,9.1,5
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.99567,3.15,0.46,10.9,5
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.99530,3.13,0.59,10.5,6

In [3]:
# renomear coluna índice
data.index.names = ['wine']

In [4]:
# modificar nomes das colunas

cols = {}
for col in data.columns:
    newcol = col.lower().replace(' ', '_')
    cols[col] = newcol
    #print(col, '=>', newcol)

#print(type(cols), cols)

data.rename(columns=cols, inplace=True)

# aumentar a precisão da coluna alvo
data.quality = round(data.quality + 1e-3, 2)

In [7]:
data.quality = data.quality.map(lambda x: 'good' if x > 6 else 'bad')

In [10]:
data['quality'].describe()

count     4898
unique       2
top        bad
freq      3838
Name: quality, dtype: object

In [11]:
# exibir dados
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.99740,3.04,0.53,8.9,bad
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.99347,3.24,0.46,10.4,good
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.99750,3.23,0.48,9.1,bad
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.99567,3.15,0.46,10.9,bad
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.99530,3.13,0.59,10.5,bad

In [12]:
# dividir os dados de treino e teste

divisao = int(data.shape[0] * 2 / 3)

train = data[:divisao]
test = data[divisao:]

print(train.shape, test.shape)

(3265, 12) (1633, 12)

In [13]:
train.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.99740,3.04,0.53,8.9,bad
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.99347,3.24,0.46,10.4,good
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.99750,3.23,0.48,9.1,bad
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.99567,3.15,0.46,10.9,bad
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.99530,3.13,0.59,10.5,bad

In [14]:
test.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
3123,5.5,0.18,0.22,5.5,0.037,10.0,86.0,0.99156,3.46,0.44,12.2,bad
3903,5.8,0.27,0.26,3.5,0.071,26.0,69.0,0.98994,3.10,0.38,11.5,bad
3104,7.6,0.21,0.49,2.5,0.047,20.0,130.0,0.99178,3.15,0.48,11.1,bad
4190,7.0,0.22,0.30,1.4,0.040,14.0,63.0,0.98985,3.20,0.33,12.0,bad
2133,8.3,0.24,0.27,2.1,0.030,22.0,162.0,0.99140,2.99,0.68,11.9,bad

In [15]:
example = test[['quality']]
#example['quality'] = example.index.map(lambda x: float(x % 7 + 3))
example['quality'] = example.index.map(lambda x: 'good' if (x % 7 == 0) else 'bad')
example.head()

/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

     quality
wine
3123     bad
3903     bad
3104     bad
4190     bad
2133     bad

In [16]:
example.describe()

       quality
count     1633
unique       2
top        bad
freq      1406

In [17]:
train.to_csv('wine-train.csv')

test.drop(['quality'], axis=1).to_csv('wine-test.csv')
test[['quality']].to_csv('wine-solution.csv')

example.to_csv('wine-example.csv')

In [18]:
!head wine-*.csv

==> wine-example.csv <==
wine,quality
3123,bad
3903,bad
3104,bad
4190,bad
2133,bad
2870,good
3876,bad
2937,bad
2195,bad

==> wine-solution.csv <==
wine,quality
3123,bad
3903,bad
3104,bad
4190,bad
2133,bad
2870,good
3876,bad
2937,bad
2195,bad

==> wine-test.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol
3123,5.5,0.18,0.22,5.5,0.037,10.0,86.0,0.99156,3.46,0.44,12.2
3903,5.8,0.27,0.26,3.5,0.071,26.0,69.0,0.98994,3.1,0.38,11.5
3104,7.6,0.21,0.49,2.5,0.047,20.0,130.0,0.99178,3.15,0.48,11.1
4190,7.0,0.22,0.3,1.4,0.04,14.0,63.0,0.98985,3.2,0.33,12.0
2133,8.3,0.24,0.27,2.1,0.03,22.0,162.0,0.9914,2.99,0.68,11.9
2870,6.7,0.48,0.32,1.4,0.021,22.0,121.0,0.9889,3.15,0.53,12.7
3876,6.1,0.22,0.28,16.55,0.059,54.0,135.0,0.99665,3.2,0.38,10.5
2937,7.7,0.25,0.3,7.8,0.038,67.0,196.0,0.99555,3.1,0.5,10.1
2195,6.8,0.25,0.18,1.4,0.056,13.0,137.0,0.9935,3.11,0.42,9.5

==> wine-train-scaled.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
1942,0.4271844660194176,0.3163841807909604,0.3433734939759036,0.22085889570552147,0.14726027397260275,0.24175824175824173,0.8125,0.250433776749567,0.19090909090909092,0.48837209302325574,0.09999999999999987,0.33333333333333326
3847,0.24271844660194186,0.2711864406779661,0.1385542168674699,0.23926380368098157,0.15753424657534248,0.2490842490842491,0.549342105263158,0.22151532677848706,0.49090909090909074,0.372093023255814,0.18333333333333335,0.33333333333333326
3183,0.2524271844660194,0.1807909604519774,0.22891566265060243,0.006134969325153375,0.06164383561643837,0.21245421245421245,0.2664473684210526,0.04144977829188434,0.4727272727272731,0.16279069767441856,0.7166666666666666,0.5
2745,0.27184466019417486,0.4067796610169492,0.13253012048192772,0.0567484662576687,0.07876712328767124,0.12454212454212454,0.29605263157894735,0.0586080586080584,0.49090909090909074,0.3604651162790698,0.8,0.6666666666666665
2977,0.2621359223300971,0.1694915254237288,0.12048192771084339,0.16564417177914112,0.11986301369863016,0.315018315018315,0.4013157894736842,0.17216117216117155,0.21818181818181825,0.3372093023255814,0.2833333333333332,0.5
1421,0.22330097087378642,0.11299435028248586,0.29518072289156627,0.0598159509202454,0.13013698630136986,0.10989010989010989,0.2664473684210526,0.0923462502409862,0.5,0.17441860465116277,0.5999999999999999,0.5
1709,0.2815533980582524,0.15819209039548024,0.18072289156626506,0.19938650306748465,0.15753424657534248,0.3516483516483516,0.5625,0.21765953344900524,0.6545454545454548,0.19767441860465118,0.30000000000000004,0.33333333333333326
4601,0.2912621359223302,0.1694915254237288,0.21084337349397592,0.09662576687116564,0.07191780821917809,0.315018315018315,0.35197368421052627,0.10275689223057682,0.07272727272727275,0.372093023255814,0.5,0.5
2326,0.2912621359223302,0.30508474576271183,0.33132530120481934,0.174079754601227,0.09931506849315071,0.14652014652014653,0.3355263157894737,0.18816271447850497,0.3545454545454545,0.08139534883720928,0.2833333333333332,0.33333333333333326

==> wine-train-without-outliers.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality,outlier
1942,8.3,0.36,0.57,15.0,0.052,35.0,256.0,1.0001,2.93,0.64,8.6,5.0,False
3183,6.5,0.24,0.38,1.0,0.027,31.0,90.0,0.98926,3.24,0.36,12.3,6.0,False
2745,6.7,0.44,0.22,4.3,0.032,19.0,99.0,0.99015,3.26,0.53,12.8,7.0,False
2977,6.6,0.23,0.2,11.4,0.044,45.0,131.0,0.99604,2.96,0.51,9.7,6.0,False
1421,6.2,0.18,0.49,4.5,0.047,17.0,90.0,0.9919,3.27,0.37,11.6,6.0,False
1709,6.8,0.22,0.3,13.6,0.055,50.0,180.0,0.9984,3.44,0.39,9.8,5.0,False
4601,6.9,0.23,0.35,6.9,0.03,45.0,116.0,0.99244,2.8,0.54,11.0,6.0,False
2326,6.9,0.35,0.55,11.95,0.038,22.0,111.0,0.99687,3.11,0.29,9.7,5.0,False
2922,6.5,0.44,0.47,5.45,0.014,44.0,137.0,0.98984,3.13,0.32,13.0,8.0,False

==> wine-train.csv <==
wine,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
4783,6.7,0.3,0.5,12.1,0.045,38.0,127.0,0.9974,3.04,0.53,8.9,bad
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.99347,3.24,0.46,10.4,good
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.9975,3.23,0.48,9.1,bad
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.99567,3.15,0.46,10.9,bad
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.9953,3.13,0.59,10.5,bad
4708,7.2,0.33,0.28,1.4,0.034,26.0,109.0,0.99246,3.28,0.57,10.6,bad
3295,6.6,0.28,0.41,7.0,0.046,59.0,194.0,0.99558,3.14,0.48,9.4,bad
2742,8.0,0.23,0.28,2.7,0.048,49.0,165.0,0.9952,3.26,0.72,9.5,bad
2969,6.7,0.2,0.3,1.4,0.025,17.0,76.0,0.99104,3.11,0.44,11.0,bad