## Importação dos pacotes

In [83]:
# importar pacotes necessários
import numpy as np
import pandas as pd

In [84]:
# definir parâmetros extras
pd.set_option('precision', 3)
pd.set_option('display.max_columns', 100)

## Carga dos dados

In [85]:
# carregar arquivo de dados de treino
data = pd.read_csv('wine-train.csv', index_col='wine')

# mostrar alguns exemplos de registros
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.997,3.04,0.53,8.9,bad
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.993,3.24,0.46,10.4,good
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.998,3.23,0.48,9.1,bad
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.996,3.15,0.46,10.9,bad
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.995,3.13,0.59,10.5,bad

In [86]:
# quantas linhas e colunas existem?
data.shape

(3265, 12)

## Análise dos dados

In [87]:
# quais são as colunas e respectivos tipos de dados?
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3265 entries, 4783 to 2658
Data columns (total 12 columns):
fixed_acidity           3265 non-null float64
volatile_acidity        3265 non-null float64
citric_acid             3265 non-null float64
residual_sugar          3265 non-null float64
chlorides               3265 non-null float64
free_sulfur_dioxide     3265 non-null float64
total_sulfur_dioxide    3265 non-null float64
density                 3265 non-null float64
ph                      3265 non-null float64
sulphates               3265 non-null float64
alcohol                 3265 non-null float64
quality                 3265 non-null object
dtypes: float64(11), object(1)
memory usage: 318.8+ KB

In [88]:
# existem colunas com dados nulos?
data[data.columns[data.isnull().any()]].isnull().sum()

Series([], dtype: float64)

In [89]:
data.isna().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
ph                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [90]:
# sumário estatístico das características numéricas
data.describe().T

,count,mean,std,min,25%,50%,75%,max
fixed_acidity,3265.0,6.857,0.857,3.900,6.300,6.800,7.300,11.800
volatile_acidity,3265.0,0.278,0.101,0.080,0.210,0.260,0.320,1.005
citric_acid,3265.0,0.334,0.123,0.000,0.260,0.320,0.390,1.230
residual_sugar,3265.0,6.442,5.093,0.600,1.700,5.300,9.900,65.800
chlorides,3265.0,0.045,0.021,0.009,0.036,0.043,0.050,0.290
free_sulfur_dioxide,3265.0,35.447,17.321,2.000,23.000,34.000,46.000,289.000
total_sulfur_dioxide,3265.0,138.221,42.324,9.000,108.000,134.000,167.000,440.000
density,3265.0,0.994,0.003,0.987,0.992,0.994,0.996,1.039
ph,3265.0,3.186,0.151,2.740,3.080,3.180,3.280,3.820
sulphates,3265.0,0.489,0.114,0.220,0.410,0.470,0.550,1.080
alcohol,3265.0,10.520,1.231,8.000,9.500,10.400,11.400,14.050

In [91]:
# quais as correlações entre as características numéricas?
data.corr()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol
fixed_acidity,1.000,-0.013,0.293,0.099,0.010,-4.997e-02,0.080,0.269,-4.382e-01,-0.016,-0.112
volatile_acidity,-0.013,1.000,-0.152,0.070,0.051,-9.582e-02,0.077,0.030,-1.996e-02,-0.036,0.090
citric_acid,0.293,-0.152,1.000,0.097,0.146,8.185e-02,0.116,0.158,-1.710e-01,0.058,-0.085
residual_sugar,0.099,0.070,0.097,1.000,0.073,2.729e-01,0.379,0.836,-1.979e-01,-0.021,-0.425
chlorides,0.010,0.051,0.146,0.073,1.000,9.208e-02,0.192,0.252,-8.321e-02,0.012,-0.378
free_sulfur_dioxide,-0.050,-0.096,0.082,0.273,0.092,1.000e+00,0.627,0.275,6.917e-04,0.045,-0.247
total_sulfur_dioxide,0.080,0.077,0.116,0.379,0.192,6.270e-01,1.000,0.513,2.462e-02,0.123,-0.442
density,0.269,0.030,0.158,0.836,0.252,2.747e-01,0.513,1.000,-9.447e-02,0.076,-0.760
ph,-0.438,-0.020,-0.171,-0.198,-0.083,6.917e-04,0.025,-0.094,1.000e+00,0.148,0.119
sulphates,-0.016,-0.036,0.058,-0.021,0.012,4.539e-02,0.123,0.076,1.482e-01,1.000,-0.013
alcohol,-0.112,0.090,-0.085,-0.425,-0.378,-2.468e-01,-0.442,-0.760,1.185e-01,-0.013,1.000

In [92]:
# show variable correlation which is more than 0.6 (positive or negative)
corr = data.corr()
corr[corr != 1][abs(corr) > 0.6].dropna(how='all', axis=1).dropna(how='all', axis=0)

,residual_sugar,free_sulfur_dioxide,total_sulfur_dioxide,density,alcohol
residual_sugar,NaN,NaN,NaN,0.836,NaN
free_sulfur_dioxide,NaN,NaN,0.627,NaN,NaN
total_sulfur_dioxide,NaN,0.627,NaN,NaN,NaN
density,0.836,NaN,NaN,NaN,-0.76
alcohol,NaN,NaN,NaN,-0.760,NaN

In [93]:
data.groupby('quality').mean()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol
quality,,,,,,,,,,,
bad,6.889,0.281,0.337,6.724,0.048,35.795,141.800,0.994,3.179,0.486,10.263
good,6.742,0.267,0.325,5.422,0.038,34.192,125.316,0.992,3.209,0.498,11.445

numeric_feats = data.dtypes[data.dtypes != "object"].index
numeric_feats

from scipy.stats import skew
skewed_feats = data[numeric_feats].apply(lambda x: skew(x.dropna())) # compute skewness
skewed_feats = skewed_feats[skewed_feats > 0.75]
skewed_feats = skewed_feats.index
skewed_feats

data.head(10).T

data[skewed_feats] = np.log1p(data[skewed_feats])

data.head(10).T

data = pd.get_dummies(data)
data = data.fillna(data.mean())

# carregar arquivo de dados de treino (normalizados)
data = pd.read_csv('wine-train-scaled.csv', index_col='wine')

# https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba

Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

print(IQR)

'''
print('')
print(data.mean())
print('')
print(data.std())
'''

print(data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))

# https://www.kdnuggets.com/2017/02/removing-outliers-standard-deviation-python.html

#TODO: remover outliers para cada valor de "quality" (de 3 a 9)

spread = 3

removed_ids = ((data < (Q1 - spread * IQR)) | (data > (Q3 + spread * IQR))).index.values
print('removed ids:', removed_ids)

data_out = data[~((data < (Q1 - spread * IQR)) | (data > (Q3 + spread * IQR))).any(axis=1)]
#data_out = data[~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)]

print('before:', data.shape, '=> after:', data_out.shape,
      ':: removed %d lines' % int(data.shape[0] - data_out.shape[0]))

data_out.head(10).T

data_out.to_csv('wine-train-without-outliers.csv')

dtqu = data.drop(['quality'], axis=1).head()
Q1 = dtqu.quantile(0.25)
Q3 = dtqu.quantile(0.75)
IQR = Q3 - Q1
IQR

(dtqu < (Q1 - spread * IQR)).head()

In [102]:
spread = 0.5

data['outlier'] = False

for quality in ['good', 'bad']:
#for quality in np.arange(3, 10):
#if (True):

    #quality = 5
    dtqu = data[data.quality == quality].drop(['quality'], axis=1)
    
    Q1 = dtqu.quantile(0.25)
    Q3 = dtqu.quantile(0.75)
    IQR = Q3 - Q1
    
    removed_ids = ~((dtqu < (Q1 - spread * IQR)) | (dtqu > (Q3 + spread * IQR))).any(axis=1)
    df_rids = pd.DataFrame(data=removed_ids, columns=['outlier'])
    
    data.update(df_rids)
    
    #print(quality, dtqu[dtqu.outlier == True].count())
    print(quality, data[data.outlier == False].shape[0])

good 3088
bad 2630

In [103]:
removed_ids.head()

wine
4783    False
2303    False
4254    False
1593    False
4708     True
dtype: bool

In [104]:
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality,outlier
wine,,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.997,3.04,0.53,8.9,bad,False
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.993,3.24,0.46,10.4,good,False
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.998,3.23,0.48,9.1,bad,False
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.996,3.15,0.46,10.9,bad,False
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.995,3.13,0.59,10.5,bad,False

In [105]:
data[['ph','outlier']].groupby('outlier').count()

           ph
outlier
False    2630
True      635

In [77]:
data_without_outliers = data[data.outlier == False].drop(['outlier'], axis=1)
data_without_outliers.shape

(2630, 12)

In [78]:
data_without_outliers.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.997,3.04,0.53,8.9,bad
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.993,3.24,0.46,10.4,good
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.998,3.23,0.48,9.1,bad
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.996,3.15,0.46,10.9,bad
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.995,3.13,0.59,10.5,bad

In [79]:
data_without_outliers.to_csv('wine-train-without-outliers.csv')

In [80]:
data = data_without_outliers
data.quality = data.quality.map({'good': 1, 'bad': 0})
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,6.7,0.30,0.50,12.1,0.045,38.0,127.0,0.997,3.04,0.53,8.9,0
2382,6.9,0.15,0.28,4.4,0.029,14.0,107.0,0.993,3.24,0.46,10.4,1
2303,6.9,0.44,0.18,11.8,0.051,26.0,126.0,0.998,3.23,0.48,9.1,0
4254,7.5,0.29,0.24,9.9,0.058,25.0,115.0,0.996,3.15,0.46,10.9,0
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.995,3.13,0.59,10.5,0

In [81]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(data))

data_filtered_scaled = pd.DataFrame(scaler.transform(data), columns=data.columns, index=data.index)
data_filtered_scaled.head()

MinMaxScaler(copy=True, feature_range=(0, 1))

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
wine,,,,,,,,,,,,
4783,0.354,0.238,0.407,0.176,0.128,0.125,0.274,0.198,0.278,0.360,0.149,0.0
2382,0.380,0.076,0.228,0.058,0.071,0.042,0.227,0.123,0.463,0.279,0.397,1.0
2303,0.380,0.389,0.146,0.172,0.149,0.084,0.271,0.200,0.454,0.302,0.182,0.0
4254,0.456,0.227,0.195,0.143,0.174,0.080,0.246,0.165,0.380,0.279,0.479,0.0
1593,0.595,0.086,0.398,0.103,0.121,0.024,0.125,0.158,0.361,0.430,0.413,0.0

In [82]:
data_filtered_scaled.to_csv('wine-train-filtered-scaled.csv')